name: "Build and deploy app"
on:
  workflow_dispatch:
  push:
    branches:
      - "beta"
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "16"
      - name: "Install dependencies"
        run: "yarn"
      - name: "Build app"
        run: "yarn run build"
